testDijkstra (__main__.TestAlgo) ... FAIL
testIndiceMinimum (__main__.TestAlgo) ... FAIL
testNoeudMinimalNonVisitesDeNoeudA (__main__.TestAlgo) ... FAIL
testNoeudMinimalNonVisitesDeNoeudB (__main__.TestAlgo) ... FAIL
testNoeudsVoisinsA (__main__.TestAlgo) ... FAIL
testNoeudsVoisinsB (__main__.TestAlgo) ... FAIL
testnoeudMinimalNonVisites (__main__.TestAlgo) ... FAIL
testCarteEnSommets (__main__.TestCarte) ... FAIL
testDistance3D (__main__.TestCarte) ... FAIL
testDistanceEuclidienne (__main__.TestCarte) ... FAIL
testEstVoisinA (__main__.TestCarte) ... ok
testEstVoisinB (__main__.TestCarte) ... FAIL
testChargeMatriceDeCarte (__main__.TestFichier) ... FAIL
testLireCarte (__main__.TestFichier) ... FAIL
testAfficheChemin (__main__.TestInterface) ... FAIL
testGenereMatriceAleatoireA (__main__.TestInterface) ... FAIL
testGenereMatriceAleatoireB (__main__.TestInterface) ... ERROR
testSaisirMatrice (__main__.TestInterface) ... FAIL

======================================================================
ERROR: testGenereMatriceAleatoireB (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 176, in testGenereMatriceAleatoireB
    for i, ligne in enumerate(matrice):
TypeError: 'ellipsis' object is not iterable

======================================================================
FAIL: testDijkstra (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 118, in testDijkstra
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testIndiceMinimum (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 72, in testIndiceMinimum
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudMinimalNonVisitesDeNoeudA (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 80, in testNoeudMinimalNonVisitesDeNoeudA
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudMinimalNonVisitesDeNoeudB (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 88, in testNoeudMinimalNonVisitesDeNoeudB
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudsVoisinsA (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 103, in testNoeudsVoisinsA
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testNoeudsVoisinsB (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 110, in testNoeudsVoisinsB
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testnoeudMinimalNonVisites (__main__.TestAlgo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 95, in testnoeudMinimalNonVisites
    self.assertTupleEqual(tuple_1, tuple_2)
AssertionError: First sequence is not a tuple: Ellipsis

======================================================================
FAIL: testCarteEnSommets (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 148, in testCarteEnSommets
    self.assertDictEqual(sommets, carte_data_ex["sommets"])
AssertionError: Ellipsis is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: testDistance3D (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 143, in testDistance3D
    self.assertEqual(distance, carte_data_ex["distance_4"])
AssertionError: Ellipsis != 8.306623862918075

======================================================================
FAIL: testDistanceEuclidienne (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 137, in testDistanceEuclidienne
    self.assertEqual(distance, carte_data_ex["distance_3"])
AssertionError: Ellipsis != 2.23606797749979

======================================================================
FAIL: testEstVoisinB (__main__.TestCarte)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 131, in testEstVoisinB
    self.assertFalse(estVoisin(sommet1, sommet2))
AssertionError: Ellipsis is not false

======================================================================
FAIL: testChargeMatriceDeCarte (__main__.TestFichier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 160, in testChargeMatriceDeCarte
    self.assertListEqual(carte, fichier_data_ex["carte_2"])
AssertionError: First sequence is not a list: Ellipsis

======================================================================
FAIL: testLireCarte (__main__.TestFichier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 155, in testLireCarte
    self.assertListEqual(carte, fichier_data_ex["carte_1"])
AssertionError: First sequence is not a list: Ellipsis

======================================================================
FAIL: testAfficheChemin (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 190, in testAfficheChemin
    self.assertMultiLineEqual(interface_data_ex["txt"], txt)
AssertionError: Ellipsis is not an instance of <class 'str'> : Second argument is not a string

======================================================================
FAIL: testGenereMatriceAleatoireA (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assignment.py", line 170, in testGenereMatriceAleatoireA
    self.assertTrue(isinstance(genereMatriceAleatoire(5), list))
AssertionError: False is not true

======================================================================
FAIL: testSaisirMatrice (__main__.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "test_assignment.py", line 167, in testSaisirMatrice
    self.assertListEqual(saisirMatrice(), matrice)
AssertionError: First sequence is not a list: Ellipsis

----------------------------------------------------------------------
Ran 18 tests in 0.016s

FAILED (failures=16, errors=1)
